# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.io import (
    load_spatial_features_group as load_spatial_features_group,
)
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_gee_connection as set_gee_connection
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from vcf_basemap.tasks import collect_dashboard_widgets as collect_dashboard_widgets
from vcf_basemap.tasks import create_vcf_basemap as create_vcf_basemap
from vcf_basemap.tasks import draw_vcf_legend as draw_vcf_legend
from vcf_basemap.tasks import draw_vcf_preview as draw_vcf_preview
from vcf_basemap.tasks import set_vcf_palette as set_vcf_palette
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    gee_conn = (
        task(set_gee_connection)
        .validate()
        .set_task_instance_id("gee_conn")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("gee_conn") or {}))
        .call()
    )

    roi = (
        task(load_spatial_features_group)
        .validate()
        .set_task_instance_id("roi")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("roi") or {}))
        .call()
    )

    vcf_palette = (
        task(set_vcf_palette)
        .validate()
        .set_task_instance_id("vcf_palette")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("vcf_palette") or {}))
        .call()
    )

    vcf_export = (
        task(create_vcf_basemap)
        .validate()
        .set_task_instance_id("vcf_export")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_conn,
            palette=vcf_palette,
            roi=roi,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("vcf_export") or {}),
        )
        .call()
    )

    vcf_preview = (
        task(draw_vcf_preview)
        .validate()
        .set_task_instance_id("vcf_preview")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_conn,
            palette=vcf_palette,
            roi=roi,
            **(params.get("vcf_preview") or {}),
        )
        .call()
    )

    persist_preview = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_preview")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=vcf_preview,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="basemap",
            **(params.get("persist_preview") or {}),
        )
        .call()
    )

    map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="VCF Basemap",
            view=None,
            data=persist_preview,
            **(params.get("map_widget") or {}),
        )
        .call()
    )

    vcf_legend = (
        task(draw_vcf_legend)
        .validate()
        .set_task_instance_id("vcf_legend")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            palette=vcf_palette,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("vcf_legend") or {}),
        )
        .call()
    )

    persist_legend = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_legend")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            text=vcf_legend,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="legend",
            **(params.get("persist_legend") or {}),
        )
        .call()
    )

    legend_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("legend_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Endmember Triangle (VCF)",
            view=None,
            data=persist_legend,
            **(params.get("legend_widget") or {}),
        )
        .call()
    )

    collect_widgets = (
        task(collect_dashboard_widgets)
        .validate()
        .set_task_instance_id("collect_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            map_widget=map_widget,
            legend_widget=legend_widget,
            **(params.get("collect_widgets") or {}),
        )
        .call()
    )

    vcf_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("vcf_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=collect_widgets,
            groupers=None,
            time_range=None,
            **(params.get("vcf_dashboard") or {}),
        )
        .call()
    )

    return vcf_dashboard
